"use strict";

const test=require("node:test");const assert=require("node:assert/strict");
const {loadAiConfig}=require("../src/ai/config");const {analyzeSnapshot}=require("../src/ai/analyzer");
const {buildPayload}=require("../src/ai/providers");const {toRow}=require("../src/ai/store");

test("all providers are disabled by default",()=>{const config=loadAiConfig({});assert.equal(config.enabled,false);assert.ok(Object.values(config.providers).every(x=>!x.enabled));});
test("supports three providers with provider-specific settings",()=>{const config=loadAiConfig({AI_ANALYSIS_ENABLED:"true",PERPLEXITY_ENABLED:"true",XAI_ENABLED:"true",DEEPSEEK_ENABLED:"true",PERPLEXITY_API_KEY:"p",XAI_API_KEY:"x",DEEPSEEK_API_KEY:"d",DEEPSEEK_TIMEOUT_MS:"4321"});assert.deepEqual(Object.keys(config.providers),["perplexity","xai","deepseek"]);assert.equal(config.providers.deepseek.timeoutMs,4321);assert.equal(config.providers.deepseek.model,"deepseek-v4-flash");});
test("mock analysis isolates provider errors and never calls the network",async()=>{
  const config=loadAiConfig({AI_ANALYSIS_ENABLED:"true",AI_MAX_COST_USD_PER_RUN:"1",PERPLEXITY_ENABLED:"true",XAI_ENABLED:"true",DEEPSEEK_ENABLED:"true",PERPLEXITY_API_KEY:"p",XAI_API_KEY:"x",DEEPSEEK_API_KEY:"d"});const calls=[];
  const transport=async request=>{calls.push(request.endpoint);if(request.endpoint.includes("api.x.ai")){const e=new Error("mock failure");e.code="HTTP_503";throw e;}return {body:{choices:[{message:{content:JSON.stringify({summary:"read-only",sentiment:"neutral",confidence:.8,signals:["stable"]})}}]},usage:{prompt_tokens:10,completion_tokens:5,raw:"must not persist"}};};
  const results=await analyzeSnapshot({market_score:50},config,{transport});assert.equal(calls.length,3);assert.deepEqual(results.map(x=>x.status),["success","error","success"]);assert.equal(results[1].errorCode,"HTTP_503");assert.deepEqual(results[0].usage,{prompt_tokens:10,completion_tokens:5});
});
test("cost limit skips providers before transport",async()=>{const config=loadAiConfig({AI_ANALYSIS_ENABLED:"true",AI_MAX_COST_USD_PER_RUN:"0",PERPLEXITY_ENABLED:"true",PERPLEXITY_API_KEY:"p"});let called=false;const results=await analyzeSnapshot({market_score:50},config,{transport:async()=>{called=true;}});assert.equal(called,false);assert.equal(results[0].status,"skipped");});
test("oversized input is bounded without breaking JSON payload creation",async()=>{const config=loadAiConfig({AI_ANALYSIS_ENABLED:"true",AI_MAX_INPUT_CHARS:"1000",AI_MAX_COST_USD_PER_RUN:"1",DEEPSEEK_ENABLED:"true",DEEPSEEK_API_KEY:"d"});let captured;await analyzeSnapshot({large:"x".repeat(5000)},config,{transport:async request=>{captured=request.payload;return {body:{choices:[{message:{content:'{"summary":"ok","sentiment":"neutral","confidence":0,"signals":[]}'}}]},usage:{}};}});const input=JSON.parse(captured.messages[1].content);assert.equal(input.truncated,true);assert.ok(input.snapshotText.length<=1000);});
test("stored row contains normalized fields and no raw response",()=>{const row=toRow({provider:"deepseek",model:"deepseek-v4-flash",status:"success",summary:"ok",sentiment:"neutral",confidence:.5,signals:["one"],usage:{total_tokens:5},costUsd:.001},"2026-01-01T00:00:00Z");assert.deepEqual(Object.keys(row),["source_snapshot_ts","provider","model","status","summary","sentiment","confidence","signals","usage","cost_usd","error_code"]);assert.equal(JSON.stringify(row).includes("response"),false);});
test("DeepSeek payload is read-only JSON analysis",()=>{const config=loadAiConfig({AI_ANALYSIS_ENABLED:"true",DEEPSEEK_ENABLED:"true",DEEPSEEK_API_KEY:"secret"});const payload=buildPayload(config.providers.deepseek,{market_score:55});assert.equal(payload.model,"deepseek-v4-flash");assert.deepEqual(payload.thinking,{type:"disabled"});assert.match(payload.messages[0].content,/Never recommend or create orders/);assert.equal(JSON.stringify(payload).includes("secret"),false);});
