"use strict";
const test=require('node:test'),assert=require('node:assert/strict');
const {chartEvidence,relativeStrength,ratesEvidence}=require('../src/gn-live-verification');
const {createFundamentalService}=require('../src/gn-fundamentals');
const now=Date.parse('2026-10-05T12:00:00Z'),day=86400000;
function chart(){return {chart:{result:[{meta:{currency:'USD',regularMarketPrice:150,regularMarketTime:(now-3600000)/1000},timestamp:Array.from({length:250},(_,i)=>(now-day*(250-i))/1000),indicators:{adjclose:[{adjclose:Array.from({length:250},(_,i)=>100+i)}]}}]}};}
test('dated real price and 200 observations are verified separately from investment conditions',()=>{const c=chartEvidence(chart(),'VRT',now);assert.equal(c.price_verified,true);assert.equal(c.chart_verified,true);const b=chartEvidence(chart(),'SPY',now);assert.equal(relativeStrength(c,b).verified,true);assert.equal(relativeStrength(c,b).rs_1m,0);});
test('stale, duplicate and missing candles cannot create verified chart evidence',()=>{const d=chart();d.chart.result[0].timestamp[249]=d.chart.result[0].timestamp[248];assert.equal(chartEvidence(d,'VRT',now).chart_verified,false);assert.equal(chartEvidence(chart(),'VRT',now+10*day).price_verified,false);});
test('FRED compares aligned real yields and breakevens without passing investment gates',()=>{const csv='observation_date,DGS2,DGS10,DGS30,DFII10,T10YIE\n'+Array.from({length:6},(_,i)=>`2026-09-${25+i},4,5,6,2,3`).join('\n');const r=ratesEvidence(csv,now);assert.equal(r.verified,true);assert.equal(r.changes_5_sessions.DGS10,0);assert.ok(r.reason.includes('텀프리미엄 별도 미확인'));assert.equal(ratesEvidence('date,DGS2\n2026-10-05,4',now).verified,false);});
test('blocked storage retains direct collection and avoids repeated quota requests',async()=>{let calls=0;const db={from(){return {insert:async()=>{calls++;return {error:{status:402}};},select(){throw Error('402');}};}};const s=createFundamentalService(db,async(symbol,at)=>({symbol,observed_at:new Date(at).toISOString(),checks:{cashflow:{sources:['SEC'],metrics:{ocf_ttm:10}}}}),()=>now);await s.refresh();const r=await s.read();assert.equal(r.items.length,4);assert.equal(r.storage_status,'UNAVAILABLE');assert.ok(calls<=4);const count=calls;await s.read();assert.equal(calls,count);});
